# Generated by Django 5.1 on 2024-08-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeLastProjects', '0001_initial'),
        ('MyResumeSkill', '0003_alter_userskill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastprojects',
            name='users',
        ),
        migrations.AddField(
            model_name='lastprojects',
            name='OtherSubSkill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lastprojects',
            name='UserSubSkill',
            field=models.ManyToManyField(blank=True, null=True, related_name='LastProjects', to='MyResumeSkill.usersubskill'),
        ),
    ]
