# Generated by Django 5.1 on 2024-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeLastProjects', '0002_remove_lastprojects_users_lastprojects_othersubskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastprojectgallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lastprojectgallery',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lastprojects',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lastprojects',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
