# Generated by Django 5.1 on 2024-08-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeLastProjects', '0003_lastprojectgallery_is_active_and_more'),
        ('MyResumeSkill', '0005_usersubskill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastprojects',
            name='UserSkill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LastProject', to='MyResumeSkill.userskill'),
        ),
    ]
