# Generated by Django 5.1 on 2024-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeLastProjects', '0004_alter_lastprojects_userskill'),
        ('MyResumeSkill', '0005_usersubskill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastprojects',
            name='UserSubSkill',
            field=models.ManyToManyField(blank=True, null=True, related_name='LastProject', to='MyResumeSkill.usersubskill'),
        ),
    ]
