# Generated by Django 5.1 on 2024-08-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeSkill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubskill',
            name='PercentTage',
            field=models.IntegerField(),
        ),
    ]
