# Generated by Django 5.1 on 2024-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeSkill', '0003_alter_userskill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_skills',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professional_skills',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userskill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubskill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubskill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
