# Generated by Django 5.1 on 2024-08-12 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactUser', to='MyResumeMainModule.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='Profile_Resume_file/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAbout', to='MyResumeMainModule.userprofile')),
            ],
        ),
    ]
