# Generated by Django 5.1 on 2024-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0002_alter_contactuser_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userprofile',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='git_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='Profile_Image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkin_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
