# Generated by Django 5.1 on 2024-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0003_rename_userprofile_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabout',
            name='about',
            field=models.TextField(),
        ),
    ]
