# Generated by Django 5.1 on 2024-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0005_userprofile_telegram_url'),
        ('MyResumeSkill', '0003_alter_userskill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabout',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserAbout', to='MyResumeSkill.usersubskill'),
        ),
    ]
