# Generated by Django 5.1 on 2024-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0006_userabout_skill'),
        ('MyResumeSkill', '0003_alter_userskill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabout',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserAbout', to='MyResumeSkill.userskill'),
        ),
    ]
