# Generated by Django 5.1 on 2024-08-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0007_alter_userabout_skill'),
        ('MyResumeSkill', '0003_alter_userskill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Showing_Main_Skill',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to='MyResumeSkill.userskill'),
            preserve_default=False,
        ),
    ]
