# Generated by Django 5.1 on 2024-08-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0009_contactuser_is_active_contactuser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Work_space',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
