# Generated by Django 5.1 on 2024-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0010_userprofile_work_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='showing_exp',
            field=models.BooleanField(default=True),
        ),
    ]
