# Generated by Django 5.1 on 2024-09-20 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0012_alter_contactuser_profile_alter_contactuser_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
