# Generated by Django 5.1 on 2024-09-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeMainModule', '0013_uservisit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='second_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_phone_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
