# Generated by Django 5.1 on 2024-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeExpAndClients', '0002_studyexpt_is_active_studyexpt_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexpt',
            name='from_date',
            field=models.DateField(),
        ),
    ]
