# Generated by Django 5.1 on 2024-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyResumeExpAndClients', '0004_workexpt_work_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexpt',
            name='responds_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workexpt',
            name='responds_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='WorkExptResponsibility',
        ),
    ]
